light:
  - platform: mqtt
    name: "WLED Lights"
    command_topic: "wled/all"
    brightness_command_topic: "wled/all"
    rgb_command_topic: "wled/all/col"
    rgb_command_template: "{{ '#%02x%02x%02x' | format(red, green, blue)}}"
    effect_command_topic : "wled/all/api"
    effect_list:
    - "[FX=00] Solid"
    - "[FX=01] Blink"
    - "[FX=02] Breathe"
    - "[FX=03] Wipe"
    - "[FX=04] Wipe Random"
    - "[FX=05] Random Colors"
    - "[FX=06] Sweep"
    - "[FX=07] Dynamic"
    - "[FX=08] Colorloop"
    - "[FX=09] Rainbow"
    - "[FX=10] Scan"
    - "[FX=11] Dual Scan"
    - "[FX=12] Fade"
    - "[FX=13] Chase"
    - "[FX=14] Chase Rainbow"
    - "[FX=15] Running"
    - "[FX=16] Saw"
    - "[FX=17] Twinkle"
    - "[FX=18] Dissolve"
    - "[FX=19] Dissolve Rnd"
    - "[FX=20] Sparkle"
    - "[FX=21] Dark Sparkle"
    - "[FX=22] Sparkle+"
    - "[FX=23] Strobe"
    - "[FX=24] Strobe Rainbow"
    - "[FX=25] Mega Strobe"
    - "[FX=26] Blink Rainbow"
    - "[FX=27] Android"
    - "[FX=28] Chase"
    - "[FX=29] Chase Random"
    - "[FX=30] Chase Rainbow"
    - "[FX=31] Chase Flash"
    - "[FX=32] Chase Flash Rnd"
    - "[FX=33] Rainbow Runner"
    - "[FX=34] Colorful"
    - "[FX=35] Traffic Light"
    - "[FX=36] Sweep Random"
    - "[FX=37] Running 2"
    - "[FX=38] Red & Blue"
    - "[FX=39] Stream"
    - "[FX=40] Scanner"
    - "[FX=41] Lighthouse"
    - "[FX=42] Fireworks"
    - "[FX=43] Rain"
    - "[FX=44] Merry Christmas"
    - "[FX=45] Fire Flicker"
    - "[FX=46] Gradient"
    - "[FX=47] Loading"
    - "[FX=48] In Out"
    - "[FX=49] In In"
    - "[FX=50] Out Out"
    - "[FX=51] Out In"
    - "[FX=52] Circus"
    - "[FX=53] Halloween"
    - "[FX=54] Tri Chase"
    - "[FX=55] Tri Wipe"
    - "[FX=56] Tri Fade"
    - "[FX=57] Lightning"
    - "[FX=58] ICU"
    - "[FX=59] Multi Comet"
    - "[FX=60] Dual Scanner"
    - "[FX=61] Stream 2"
    - "[FX=62] Oscillate"
    - "[FX=63] Pride 2015"
    - "[FX=64] Juggle"
    - "[FX=65] Palette"
    - "[FX=66] Fire 2012"
    - "[FX=67] Colorwaves"
    - "[FX=68] BPM"
    - "[FX=69] Fill Noise"
    - "[FX=70] Noise 1"
    - "[FX=71] Noise 2"
    - "[FX=72] Noise 3"
    - "[FX=73] Noise 4"
    - "[FX=74] Colortwinkle"
    - "[FX=75] Lake"
    - "[FX=76] Meteor"
    - "[FX=77] Smooth Meteor"
    - "[FX=78] Railway"
    - "[FX=79] Ripple"
    - "[FX=80] Twinklefox"

input_select:
  wled_presets:
    options:
      - "[01] Preset 1"
      - "[02] Preset 2"
      - "[03] Preset 3"
      - "[04] Preset 4"
      - "[05] Preset 5"
      - "[06] Preset 6"
      - "[07] Preset 7"
      - "[08] Preset 8"
      - "[09] Preset 9"
      - "[10] Preset 10"
      - "[11] Preset 11"
      - "[12] Preset 12"
      - "[13] Preset 13"
      - "[14] Preset 14"
      - "[15] Preset 15"
      - "[16] Preset 16"

  wled_palette_list:
    options:
      - "[00] Default"
      - "[01] Random Cycle"
      - "[02] Primary color"
      - "[03] Based on primary"
      - "[04] Set colors"
      - "[05] Based on set"
      - "[06] Party"
      - "[07] Cloud"
      - "[08] Lava"
      - "[09] Ocean"
      - "[10] Forest"
      - "[11] Rainbow"
      - "[12] Rainbow bands"
      - "[13] Sunset"
      - "[14] Rivendell"
      - "[15] Breeze"
      - "[16] Red & Blue"
      - "[17] Yellowout"
      - "[18] Analoguous"
      - "[19] Splash"
      - "[20] Pastel"
      - "[21] Sunset 2"
      - "[22] Beech"
      - "[23] Vintage"
      - "[24] Departure"
      - "[25] Landscape"
      - "[26] Beach"
      - "[27] Sherbet"
      - "[28] Hult"
      - "[29] Hult 64"
      - "[30] Drywet"
      - "[31] Jul"
      - "[32] Grintage"
      - "[33] Rewhi"
      - "[34] Tertiary"
      - "[35] Fire"
      - "[36] Icefire"
      - "[37] Cyane"
      - "[38] Light Pink"
      - "[39] Autumn"
      - "[40] Magenta"

input_number:
  ledspeed:
    name: Speed
    initial: 0
    min: 0
    max: 255
    step: 1
  ledintensity:
    name: LED Intensity
    initial: 0
    min: 0
    max: 255
    step: 1
  ledbrightness:
    name: LED Brightness
    initial: 0
    min: 0
    max: 255
    step: 1
